name: SSH Deploy

on:
  push:
    branches: [ deploy-workflow ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ssh deploy
        uses: appleboy/ssh-action@master
        env:
          TARGET: ${{ secrets.secrets.DEPLOY_TARGET }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
             cd  $TARGET
             ls
