name: SSH Deploy

on:
  push:
    branches:
      # Push events on main branch
      - main
      # Push events on main branch
      - deploy-workflow
    # Sequence of patterns matched against refs/tags
    tags:
      - v*-deploy             # Push events with deploy tags

  pull_request:
    branches:
      # Push events on main branch
      - main
    # Sequence of patterns matched against refs/tags
    tags:
      - v*-deploy             # Push events with deploy tags

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ssh deploy
        uses: appleboy/ssh-action@master
        env:
          TARGET: ${{ secrets.DEPLOY_TARGET }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          envs: TARGET
          script: |
             cd  $TARGET
             git pull
