name: SSH Deploy

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ssh deploy
        if: endsWith( github.ref, 'deploy') # run for branches or tags ending with 'deploy'
        uses: appleboy/ssh-action@master
        env:
          TARGET: ${{ secrets.DEPLOY_TARGET }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          envs: TARGET
          script: |
             cd  $TARGET
             git pull
