name: ARENA Dev Staging SSH Deploy
on:
    # Trigger the workflow on push on master
    push:
        branches:
            - master

    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: ssh deploy
              uses: appleboy/ssh-action@master
              env:
                  TARGET: ${{ secrets.ARENA_DEV1_DEPLOY_TARGET }}
              with:
                  host: ${{ secrets.ARENA_DEV1_DEPLOY_HOST }}
                  username: ${{ secrets.ARENA_DEV1_DEPLOY_USER }}
                  key: ${{ secrets.ARENA_DEV1_DEPLOY_KEY }}
                  port: ${{ secrets.DEPLOY_PORT }}
                  envs: TARGET
                  script_stop: true
                  script: |
                      cd  $TARGET
                      git checkout master
                      git fetch
                      git reset --hard origin/master
                      npm ci
                      npm run build-ci
                      cd ..
                      ./update-custom-website.sh
